--- #YAML:1.0
name:               Net-Curl-Simple
version:            0.11
abstract:           simplified Net::Curl interface
author:
    - Przemysław Iskra <sparky at pld-linux.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:    5.00
    Coro:        0
    EV:          4.00
    Net::Curl:   0.17
    POE:         0
    Test::More:  0
    URI:         0
resources:
    repository:  https://github.com/sparky/perl-Net-Curl-Simple
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
