--- #YAML:1.0
name:               Net-Curl-Simple
version:            0.04
abstract:           simplifies Net::Curl::Easy interface
author:
    - Przemysław Iskra <sparky at pld-linux.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::Curl:   0.17
    Test::More:  0
    URI:         0
resources:
    repository:  https://github.com/sparky/perl-Net-Curl-Simple
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
